### ISSUE TITLE
Typo in GGA+U VASP parameters in documentation.

### ISSUE THREAD

**Issue by raulf2012** [materialsproject/docs#59]
I believe that the reported value for `LDAUL` is incorrect in the following documentation file:

https://github.com/materialsproject/docs/blob/master/docs/methodology/gga-plus-u.md

which sets the value to 0.

To my understanding would apply the on-site interactions/corrections to the l=0 quantum number a.k.a. s-orbitals, which doesn't seem right.

More likely it was meant to be set to 2 (putting correction on d electrons), as is reported here:

https://github.com/materialsproject/pymatgen/blob/master/pymatgen/io/vasp/MPRelaxSet.yaml

**Comment by mkhorton** [comment]
Hi @raulf2012, thanks for spotting this and for reporting it! That is indeed in error.

**Comment by mkhorton** [comment]
Closed with https://github.com/materialsproject/docs/commit/4e9966319c03f73cfc2069af16f3e213a02f9ba3

**Comment by raulf2012** [comment]
Great! Thanks for the quick turn around
