### ISSUE TITLE
Fix vertical alignment of DB stats on landing page

### ISSUE THREAD

**Issue by janosh** [materialsproject/docs#85]
I’d like to suggest adding `vertical-align: top;` to `<li>` elements showing DB stats on the landing page https://materialsproject.org.

Not sure if this is the right place for this. Originally posted [here](https://matsci.org/t/fix-vertical-alignment-of-db-stats-on-landing-page/35374).

https://user-images.githubusercontent.com/30958850/107501280-80cbb680-6b97-11eb-80d1-03d2ff6bd8c1.mp4

**Comment by mkhorton** [comment]
Thanks for reporting. We have a new website in development, the current website is largely considered feature-frozen -- let us know if you'd like to be on the beta list for the new site though.

**Comment by janosh** [comment]
> let us know if you'd like to be on the beta list for the new site though.

Definitely.

**Comment by mkhorton** [comment]
Sign-up form here: https://forms.gle/EQrXv4EoxgXRCymp8

Feel free to share with others you think might be interested, we'll only be opening up to the first ~hundred names to start with.

**Comment by janosh** [comment]
@mkhorton I filled out the form you linked in Feb but don't think I've heard back yet.

**Comment by mkhorton** [comment]
It's because we haven't launched yet :)

**Comment by janosh** [comment]
I see. No rush. Just checking. Really looking forward to the workshop in August!
